   keys:
     - &yubikey age1yubikey1q09xuwg7lgchde4ssw735kzrawqyp4ur3xft4kyycrhr8ka730xgzjt0wam
   creation_rules:
     - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
       key_groups:
       - age:
         - *yubikey
